# Generated by Django 5.1.2 on 2024-11-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
